# Site settings
title: Jaleesa's Webpage
description: Modern-Blog A Elegant template for Jekyll
keywords: Modern, Blogging, Fun
author: Wferr
baseurl: "jaleesah.github.io" # the subpath of your site, e.g. /blog/
url: "https://jaleesah.github.io" # the base hostname & protocol for your site
